FROM public.ecr.aws/docker/library/alpine:3.23

RUN apk add --no-cache cmake curl-dev g++ git ninja openssl-dev zlib-dev

WORKDIR /src
COPY . .

RUN mkdir build && cd build && \
    cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTS=ON && \
    ninja

ENTRYPOINT ["/src/build/tests/resources/lambda-test-fun"]
