#!/bin/bash
#  Copyright 2018-present Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License").
#  You may not use this file except in compliance with the License.
#  A copy of the License is located at
#
#   http://aws.amazon.com/apache2.0
#
#  or in the "license" file accompanying this file. This file is distributed
#  on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
#  express or implied. See the License for the specific language governing
#  permissions and limitations under the License.

set -euo pipefail

if [ $# -ne 2 ]; then
    echo "Error: missing arguments\n"
    echo "Usage: packager.sh <binary name> <output filename>"
    exit 1
fi

PKG_BIN_PATH=$1

if [ ! -f $PKG_BIN_PATH ]; then
    echo "'$PKG_BIN_PATH' - No such file.";
    exit 1;
fi

if ! type zip > /dev/null 2>&1; then
    echo "zip utility is not found. Please install it and re-run this script"
    exit 1
fi

function package_libc_via_dpkg() {
    if type dpkg-query > /dev/null 2>&1; then
        dpkg-query --listfiles libc6 | sed -E '/\.so$|\.so\.[0-9]+$/!d'
    fi
}

function package_libc_via_rpm() {
    if type rpm > /dev/null 2>&1; then
        rpm -ql | sed -E '/\.so$|\.so\.[0-9]+$/!d'
    fi
}

PKG_BIN_FILENAME=`basename $PKG_BIN_PATH`
PKG_DIR=tmp

list=`ldd $PKG_BIN_PATH | awk '{print $(NF-1)}'`
list=$list:$(package_libc_via_dpkg):$(package_libc_via_rpm)

mkdir -p $PKG_DIR/bin
mkdir $PKG_DIR/lib

for i in $list
do
    if [[ ! -f $i ]]; then # ignore linux-vdso.so.1
        continue
    fi
    cp $i $PKG_DIR/lib
    filename=`basename $i`
    if [[ -z "${filename##ld-*}" ]]; then
        PKG_LD=$filename
        echo "Found $i. Using it as the loader."
    fi
done

# glibc's libnss_dns and libnss_files are loaded dynamically, so we add them for SSL support
# RHEL variants store them under /lib64
if [ -d /lib64 ]; then
    find /lib64 -name "libnss_dns*" | xargs -I % cp % $PKG_DIR/lib
    find /lib64 -name "libnss_files*" | xargs -I % cp % $PKG_DIR/lib
fi
# Debian variants store them under /lib
if [ -d /lib ]; then
    find /lib -name "libnss_dns*" | xargs -I % cp % $PKG_DIR/lib
    find /lib -name "libnss_files*" | xargs -I % cp % $PKG_DIR/lib
fi

launch_script="#!/bin/bash\n
\n
set -euo pipefail\n
\n
\$LAMBDA_TASK_ROOT/lib/$PKG_LD --library-path \$LAMBDA_TASK_ROOT/lib \$LAMBDA_TASK_ROOT/bin/$PKG_BIN_FILENAME \${_HANDLER}\n
"

cp $PKG_BIN_PATH $PKG_DIR/bin
echo -e $launch_script > $PKG_DIR/bootstrap
chmod +x $PKG_DIR/bootstrap
pushd $PKG_DIR > /dev/null
zip -r $PKG_DIR.zip *
ORIGIN_DIR=$(dirs -l +1)
mv $PKG_DIR.zip $ORIGIN_DIR
popd > /dev/null
rm -r $PKG_DIR
echo "Created $ORIGIN_DIR/$PKG_BIN_FILENAME.zip"


# detect OS by doing:
# if [ $(cat /etc/os-release | awk -F= '/ID_LIKE/{print $NF}') =~ "rhel" ]; then
# echo RHEL
# endif
